name       : haskell-stm
version    : 2.4.4.1
release    : 4
source     :
    - http://hackage.haskell.org/package/stm-2.4.4.1/stm-2.4.4.1.tar.gz : 8f999095ed8d50d2056fc6e185035ee8166c50751e1af8de02ac38d382bf3384
license    : BSD-3-Clause
component  : programming.haskell
summary    : A modular composable concurrency abstraction.
description: |
    A modular composable concurrency abstraction.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
