name       : haskell-stm
version    : 2.4.5.0
release    : 5
source     :
    - https://hackage.haskell.org/package/stm-2.4.5.0/stm-2.4.5.0.tar.gz : 31d7db183f13beed5c71409d12747a7f4cf3e145630553dc86336208540859a7
license    : BSD-3-Clause
component  : programming.haskell
summary    : A modular composable concurrency abstraction.
description: |
    A modular composable concurrency abstraction.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
